version: '3'
services:
  backend:
    container_name: docker-node
    restart: always
    image: faizanakhter/daraz-backend
    ports:
     - '3000:3000'
    links:
     - database

  database:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  frontend:
    container_name: AngularFront
    image: faizanakhter/frontend
    ports: 
      - 80:80
    links:
      - backend